### ISSUE TITLE
Triggering github abuse detection

### ISSUE THREAD

**Issue by nightah** [Ardakilic/alerthub#16]
I have just noticed as of today that I'm constantly getting locked out of GitHub and it looks to me it's Alerthub's constant requests that are pushing it over.

Some sort of rate limiting may need to be implemented per: https://github-tools.github.io/github/examples/ratelimit

**Comment by Ardakilic** [comment]
Hello,

The thing is that this tool doesn't use the [Releases API](https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository), but the public atom feeds directly, which don't require authentication at all. Just like https://github.com/Ardakilic/alerthub/blob/master/src/utils/rss.js#L28 . I didn't know they had implemented a rate limit to fetch atom feeds. Do api rate limits also include the public checking?

How many items do you have on your checklist? If not much, I'd try increasing the `interval` value on the config. Also, can you please share an error message for me to investigate further ?

**Comment by nightah** [comment]
I have 23 releases being watched and 11 commits.

After running for a couple of minutes I'll get the following in the logs for all the respective watched releases and commits which signifies a 429 Too Many Request:
```
fetch_url_error: This URL returned a 429 status code
    at Request.<anonymous> (/app/node_modules/rss-feed-emitter/src/Feed.js:128:28)
    at Request.emit (events.js:315:20)
    at Request.onRequestResponse (/app/node_modules/request/request.js:1066:10)
    at ClientRequest.emit (events.js:315:20)
Application booted at Sat Apr 25 2020 20:30:11 GMT+1000 (Australian Eastern Standard Time)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:610:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:479:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
Emitted 'error' event on FeedEmitter instance at:
    at FeedManager.onError (/app/node_modules/rss-feed-emitter/src/FeedManager.js:57:19)
    at Feed.handleError (/app/node_modules/rss-feed-emitter/src/Feed.js:140:20)
    at Request.<anonymous> (/app/node_modules/rss-feed-emitter/src/Feed.js:128:16)
    at Request.emit (events.js:315:20)
    [... lines matching original stack trace ...]
    at TLSSocket.emit (events.js:315:20) {
  name: 'fetch_url_error',
  feed: 'https://github.com/OpenIdentityPlatform/OpenDJ/releases.atom'
}
events.js:292
      throw er; // Unhandled 'error' event
      ^

fetch_url_error: This URL returned a 429 status code
    at Request.<anonymous> (/app/node_modules/rss-feed-emitter/src/Feed.js:128:28)
    at Request.emit (events.js:315:20)
    at Request.onRequestResponse (/app/node_modules/request/request.js:1066:10)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:610:27)
Application booted at Sat Apr 25 2020 20:30:12 GMT+1000 (Australian Eastern Standard Time)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:479:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
Emitted 'error' event on FeedEmitter instance at:
    at FeedManager.onError (/app/node_modules/rss-feed-emitter/src/FeedManager.js:57:19)
    at Feed.handleError (/app/node_modules/rss-feed-emitter/src/Feed.js:140:20)
    at Request.<anonymous> (/app/node_modules/rss-feed-emitter/src/Feed.js:128:16)
    at Request.emit (events.js:315:20)
    [... lines matching original stack trace ...]
    at TLSSocket.emit (events.js:315:20) {
  name: 'fetch_url_error',
  feed: 'https://github.com/multiarch/qemu-user-static/releases.atom'
}
events.js:292
      throw er; // Unhandled 'error' event
      ^

fetch_url_error: This URL returned a 429 status code
    at Request.<anonymous> (/app/node_modules/rss-feed-emitter/src/Feed.js:128:28)
    at Request.emit (events.js:315:20)
    at Request.onRequestResponse (/app/node_modules/request/request.js:1066:10)
    at ClientRequest.emit (events.js:315:20)
Application booted at Sat Apr 25 2020 20:30:13 GMT+1000 (Australian Eastern Standard Time)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:610:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:479:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
Emitted 'error' event on FeedEmitter instance at:
    at FeedManager.onError (/app/node_modules/rss-feed-emitter/src/FeedManager.js:57:19)
    at Feed.handleError (/app/node_modules/rss-feed-emitter/src/Feed.js:140:20)
    at Request.<anonymous> (/app/node_modules/rss-feed-emitter/src/Feed.js:128:16)
    at Request.emit (events.js:315:20)
    [... lines matching original stack trace ...]
    at TLSSocket.emit (events.js:315:20) {
  name: 'fetch_url_error',
  feed: 'https://github.com/buildkite/agent/releases.atom'
}
events.js:292
      throw er; // Unhandled 'error' event
      ^
```

If I try and visit GitHub from my desktop I'll also get a GitHub error page saying that I've triggered their abuse detection mechanism:

>Access has been restricted
You have triggered an abuse detection mechanism.
Please wait a few minutes before you try again;
in some cases this may take up to an hour.
Contact Support — GitHub Status — @githubstatus

**Comment by nightah** [comment]
Also when I was suggesting we implement some rate limiting I only specified that link for the section:

>since we're unauthenticated the limit is 60 requests per hour

I'm not entirely sure what the public rate limit for the atom feeds are but right now if I have Alerthub running it prevents me from working with GitHub.

**Comment by Ardakilic** [comment]
OK, thanks for the feedback. Nowadays sadly I'm busy due to work, but I'll try to look for ways to how to implement this. It shouldn't be that hard.

Also, I'm hosting AlertHub on a cheap VPS with 24 repositories currently being tracked. For the time being, maybe you can host elsewhere. Because, even I implement this, since you're hosting at the same IP where you do your work, it may still work but eat up all your rate limit and you may still not work as expected.

**Comment by Ardakilic** [comment]
@nightah While your IP is rate limit blocked, can you please check this?

```bash
curl -I https://github.com/Ardakilic/alerthub/releases.atom
```

This should give HTTP 429 error

Then, [generate a new access token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line), and try this:

```bash
curl -I https://github.com/Ardakilic/alerthub/releases.atom?token=yourpersonaltoken
```

where `yourpersonaltoken` is your access token.

If you see HTTP 200 (which should), I can easily implement this.

**Comment by nightah** [comment]
I've just turned Alerthub back on, if/when I'm blocked again I'll give it a try.

**Comment by nightah** [comment]
@Ardakilic I'm not sure if something has changed, but when I've noticed the failures in Alerthub I've gone to visit the same feed that it's attempting to retrieve and I do not get a 404 on my browser.

It also appears that curl is returning an appropriate result, could it perhaps be blocked based on the user-agent?

**Comment by Ardakilic** [comment]
@nightah If that's the case, it could be easily overcome:

Can you change this line: https://github.com/Ardakilic/alerthub/blob/master/src/index.js#L15

```js
const feeder = new RssFeedEmitter();
```

to something likle this and try again?

```js
const feeder = new RssFeedEmitter({ userAgent: 'Your UA string' });
```

Please pass your user agent string there to ensure it's not the case.

**Comment by Ardakilic** [comment]
Hello, I've just released version 2. This release includes the user agent string trick. I believe this should fix your issue.

**Comment by Ardakilic** [comment]
Closing due to the issue due to inactivity. If the issue keeps on happening even with the latest update which has user agent feature, please let me know.

**Comment by Ardakilic** [comment]
I've released 2.1.0, which allows users to provide their access token to access private repositories and to increase this limit. This and the user agent feature should overcome this issue.

**Comment by nightah** [comment]
Apologies for the late response @Ardakilic, I actually wasn't able to reproduce the issue after a couple days.

I'm not sure if there was a change from GitHub's side of perhaps my reduction of watched repos/commits had an overall impact.

**Comment by Ardakilic** [comment]
@nightah No worries, possibly the reduction solved the issue on your side. However, with the new version, the token (which also allows you to watch private repositories, which is a bonus) and user agent trick should fix that if ever happens again.
