### ISSUE TITLE
The url argument must be in string

### ISSUE THREAD

**Issue by mwolfaardt** [Ardakilic/alerthub#20]
Hi, in my docker container log file I get the following message and I don't know what I need to do to resolve. 

(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.,
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1),
    at Array.forEach (<anonymous>),
    at FeedManager.populateNewItemsInFeed (/usr/src/app/node_modules/rss-feed-emitter/src/FeedManager.js:85:19),
    at /usr/src/app/node_modules/rss-feed-emitter/src/FeedManager.js:88:23,
New release found! tests: disable logging of `ok` wpt!,
(node:1) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined,
    at validateString (internal/validators.js:120:11),
    at Url.parse (url.js:159:3),
    at Object.urlParse [as parse] (url.js:154:13),
    at isFeedFromGitLab (/usr/src/app/src/utils/alertHub.js:15:25),
    at Object.parseFeedData (/usr/src/app/src/utils/alertHub.js:39:46),
    at FeedEmitter.<anonymous> (/usr/src/app/src/index.js:111:36),
    at FeedEmitter.emit (events.js:314:20)

**Comment by Ardakilic** [comment]
Hello, can you please provide your configuration json file (hiding the credentials if any of course)  ? It seems it cannot read some values and I may have missed some checks.

**Comment by Ardakilic** [comment]
Closing due to inactivity.
